# Generated by Django 3.0.5 on 2020-12-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_multiple_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='manny_toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onion', models.CharField(max_length=40)),
                ('tomato', models.CharField(max_length=50)),
                ('corn', models.CharField(max_length=60)),
                ('capsicum', models.CharField(max_length=60)),
                ('cheese', models.CharField(max_length=60)),
                ('jalapeno', models.CharField(max_length=60)),
            ],
        ),
    ]
